### ISSUE TITLE
How to find & use device ID?

### ISSUE THREAD

**Issue by Pintodog** [JoshHeng/FireflyAPI#2]
I have recently been trying to get this API to work with my particular school's system, and I have followed the wiki on how to locate the `ffauth_secret`. However, the wiki doesn't mention how to find `ffauth_device_id`. All it says is:

> Device ID - String - A random string which is used to identify the device. It should be unique

Can you help me with this?

Many thanks,
- Pinto

**Comment by JoshHeng** [comment]
Hello! This is a string that you can choose
