### ISSUE TITLE
Is marking tasks as done and uploading files supported?

### ISSUE THREAD

**Issue by un-simp** [JoshHeng/FireflyAPI#7]
hello. i am researching into firefly's api to build a alternative app and stumbled upon this project.
i haven't fully looked through the docs but there doesn't seem to be a way to mark tasks as done? or submit files
if there is please reply with the way that you do it.

**Comment by un-simp** [comment]
~~ id also like to know how to auth even when they aren't logged in. i know

`/login/login.aspx?prelogin={ Get Token Endpoint URL }` 

exists but when i format it to be 

`/login/login.aspx?prelogin=example.fireflycloud.net/Login/api/gettoken?ffauth_device_id={ Device ID }&ffauth_secret=&device_id={ Device ID }&app_id={ App ID }` 
it returns 
`Error serving request: Value cannot be null. Parameter name: device_id`

because its decided that its now 
`/Login/api/gettoken?ffauth_device_id={Device Id} `
and not the full
~~

Never mind. After looking at your other project with firefly the link gets url encoded before its sent

**Comment by JoshHeng** [comment]
Hey! My main use case for Firefly was syncing the timetable, so I didn't look much into tasks.

There's a bit here however it's not fully documented - https://github.com/JoshHeng/FireflyAPI/wiki/Tasks

If you'd like to continue reverse engineering the API yourself, I'd recommend using Burpsuite - let me know if you need any help with setting it up.

Regarding authentication, could you confirm that you've replaced `{ Device ID }` with an actual ID string?

**Comment by un-simp** [comment]
> Regarding authentication, could you confirm that you've replaced `{ Device ID }` with an actual ID string?

yeah i had.

> If you'd like to continue reverse engineering the API yourself, I'd recommend using Burpsuite - let me know if you need any help with setting it up.

it looks like https://github.com/TreasonMay/FireflyAPI has this support. ill have a look into that and see how they do it
